// <auto-generated />
using System;
using FileAnalysisService.Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileAnalysisService.Migrations
{
    [DbContext(typeof(FileAnalysisDbContext))]
    [Migration("20250526142157_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileAnalysisService.Domain.Entities.FileDataHolder", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Hash")
                        .HasColumnType("integer")
                        .HasColumnName("hash");

                    b.Property<int>("ParagraphCount")
                        .HasColumnType("integer")
                        .HasColumnName("paragraphs");

                    b.Property<int>("SymbolCount")
                        .HasColumnType("integer")
                        .HasColumnName("symbols");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer")
                        .HasColumnName("words");

                    b.HasKey("FileId");

                    b.ToTable("FilesData", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
